# This is a basic workflow to help you get started with Actions

name: Worfklow for Spring boot application to be deployed on Azure VM

on:
  push:
    branches: [ dev ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checking out 
        uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: package application
        run: mvn package
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}        
          username: ${{ secrets.AZURE_USERNAME }}      
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          source: "*"      
          target: "~/source"
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}        
          username: ${{ secrets.AZURE_USERNAME }}      
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script: |
                /etc/init.d/yaml-poc stop
                mv ~/source/target/yaml-poc.jar ~/source/target/yaml-poc-old.jar
                mv ~/source/target/yaml-poc-latest.jar ~/source/target/yaml-poc.jar
                rm -rf /etc/init.d/yaml-poc
                ln -s -f ~/source/target/yaml-poc.jar /etc/init.d/yaml-poc
                /etc/init.d/yaml-poc start
